Iteration1
Azcarot/PasswordStorage pull request #1
Opened 2024-06-05 07:53 UTC by Azcarot

Поправил замечания, разделил слои, перестал передавать ключ в контекст, убрал лишние транзакции, добавил хелперы, добавил тесты, везде 80%+ кроме интерфейса через баблти, поправил падающие тесты

2024-06-10 13:56 UTC, tmvrus reviewed
- много дублируещего кода
- транзакции не к месте
- ответственности слоев не выделены: хранение, шифрование, авторизация
- странное использование передачи данных упакованных в контекст

2024-06-10 13:56 UTC, tmvrus commented on cmd/client/main.go
> +			panic(err)
паника нужна для того, что бы ее где-то перехватить
а так как она не перехватывается, то рекомендую заменить ее на log.Fatal

2024-06-10 13:56 UTC, tmvrus commented on cmd/client/main.go
> +		os.Exit(1)
log.Fatal - одна строка вместо двух

2024-06-10 13:56 UTC, tmvrus commented on cmd/server/main.go
> +	if flag.FlagDBAddr != "" {
не самая удачная конструкция, с большим блоком кода внутри  if, есть способ сделать симпотичнее
```
if flag.FlagDBAddr == "" {
log.Fatal....
}
дальше код без отступа
```

2024-06-10 13:56 UTC, tmvrus commented on internal/bubbleface/bankcarddelete.go
> +func CardDeleteModel() cardDeleteModel {
конструкторы обычно начинаются с New

2024-06-10 13:56 UTC, tmvrus commented on internal/bubbleface/bankcarddelete.go
> +	if err != nil {
надо что-то сделать с ошибкой, иначе пользователь не узнает что пошло не так

2024-06-10 13:56 UTC, tmvrus commented on internal/bubbleface/bankcarddelete.go
> +	choices, cards = deCypherBankCard(ctx, data.([]storage.BankCardResponse))
довольно странный способ передать параметры в ф-ю через контекст, в документации рекомендуется использовать только те данные, которые имеют отношение именно к этому/текущему запросу, в данном случае копируется общий секрет:
- не ясно зачем его вообще копировать
- не ясно почему нельзя его просто передать параметром ф-и, не упаковывая в контекст, и не распаковывая после

2024-06-10 13:56 UTC, tmvrus commented on internal/bubbleface/bankcarddelete.go
> +}
такая работа со строками не самый эффективный подход. рекомендую изучить
strings.Buidler
https://dev.to/schadokar/the-fastest-way-to-concatenate-strings-in-golang-5mf

2024-06-10 13:56 UTC, tmvrus commented on internal/bubbleface/bankcarddelete.go
> +	case tea.KeyMsg:
можно проще,
key, ok := msg.(tea.KeyMsg)
если не ok то там не tea.KeyMsg наверное стоит какую-то ошибку подсветить
если ok то работает с key

2024-06-10 13:56 UTC, tmvrus commented on internal/bubbleface/fileview.go
> +	case tea.KeyMsg:
вот это встречается много где в клиенте, тянет на хелпер ф-ю

2024-06-10 13:56 UTC, tmvrus commented on internal/bubbleface/fileview.go
> +	case tea.KeyMsg:
и все  что дальше в нее убрать

2024-06-10 13:56 UTC, tmvrus commented on internal/bubbleface/fileview.go
> +		}
ошибки надо хоть как-то обрабатывать

2024-06-10 13:56 UTC, tmvrus commented on internal/bubbleface/bankcardmenu.go
> +	}
вот это встречается 14 раз в проекте, хороший кандидат на хелпер

2024-06-10 13:56 UTC, tmvrus commented on internal/utils/utils.go
> +package utils
максимальное неудачное называние для пакета, пому что ничего не говорит
лучше отдельно сделать пакет с конфигом и пакет с шифрованием

2024-06-10 13:56 UTC, tmvrus commented on internal/storage/users.go
> +			tx, err := store.DB.Begin(ctx)
а зачем тут транзакция если запрос всего один?

2024-06-10 13:56 UTC, tmvrus commented on internal/storage/users.go
> +	for {
а зачем цикл?

2024-06-10 13:56 UTC, tmvrus commented on internal/storage/users.go
> +	sqlQuery := fmt.Sprintf(`SELECT login FROM users WHERE login = '%s'`, data.Login)
вот так делать не нужно, это классический пример SQL injection
https://go.dev/doc/database/sql-injection

2024-06-10 13:56 UTC, tmvrus commented on internal/storage/users.go
> +	ctx := context.Background()
контекст нужно принимать снаружи, судя по коду - он там есть

2024-06-10 13:56 UTC, tmvrus commented on internal/storage/textlite.go
> +	tx, err := store.DB.BeginTx(ctx, nil)
тут транзакция хотя запрос всего один

2024-06-10 13:56 UTC, tmvrus commented on internal/storage/textdata.go
> +	}
а зачем уровень хранения данных занимается шифрованием?

2024-06-10 13:56 UTC, tmvrus commented on internal/storage/postgressql.go
> +	jwt.MapClaims
пакет называется storage, поразумевается что он хранением должен заведовать
но, он зачем-то содержит средства авторизации

2024-06-10 13:56 UTC, tmvrus commented on internal/storage/loginpwlite.go
> +		default:
вот это все лишний код
контекст отработает без него потому что и так передается дальше в код драйвера БД

2024-06-10 14:55 UTC, Azcarot commented on cmd/client/main.go
> +			panic(err)
Поправил

2024-06-10 14:55 UTC, Azcarot commented on cmd/client/main.go
> +		os.Exit(1)
Поправил

2024-06-10 14:56 UTC, Azcarot commented on cmd/server/main.go
> +	if flag.FlagDBAddr != "" {
Да, логично, исправил

2024-06-10 15:11 UTC, Azcarot commented on internal/bubbleface/bankcarddelete.go
> +func CardDeleteModel() cardDeleteModel {
Переименовал

2024-06-10 15:14 UTC, Azcarot commented on internal/bubbleface/bankcarddelete.go
> +	if err != nil {
Добавил текст в заголовок

2024-06-11 07:59 UTC, Azcarot commented on internal/bubbleface/bankcardmenu.go
> +	}
Сделал хелпер

2024-06-11 07:59 UTC, Azcarot commented on internal/bubbleface/bankcarddelete.go
> +}
Переделал на билдер

2024-06-11 10:45 UTC, Azcarot commented on internal/bubbleface/bankcarddelete.go
> +	case tea.KeyMsg:
сделал

2024-06-11 18:58 UTC, Azcarot commented on internal/bubbleface/fileview.go
> +	case tea.KeyMsg:
Сделал на хелпере

2024-06-11 19:06 UTC, Azcarot commented on internal/storage/users.go
> +	ctx := context.Background()
Теперь беру контекст запроса

2024-06-11 19:11 UTC, Azcarot commented on internal/storage/users.go
> +			tx, err := store.DB.Begin(ctx)
убрал

2024-06-11 19:11 UTC, Azcarot commented on internal/storage/users.go
> +	for {
убрал

2024-06-13 07:57 UTC, Azcarot commented on internal/storage/users.go
> +	sqlQuery := fmt.Sprintf(`SELECT login FROM users WHERE login = '%s'`, data.Login)
Исправил

2024-06-13 08:05 UTC, Azcarot commented on internal/utils/utils.go
> +package utils
Переделал

2024-06-13 14:37 UTC, Azcarot commented on internal/storage/textdata.go
> +	}
Разделил слои, теперь шифрую отдельно

2024-06-13 14:42 UTC, Azcarot commented on internal/storage/postgressql.go
> +	jwt.MapClaims
вынес в отдельный пакет

2024-06-13 14:46 UTC, Azcarot commented on internal/storage/loginpwlite.go
> +		default:
Понял, отовсюду убрал

2024-06-13 14:52 UTC, Azcarot commented on internal/storage/textlite.go
> +	tx, err := store.DB.BeginTx(ctx, nil)
Да, запросы у меня все одиночные, так что теперь транзакции убрал

2024-06-13 14:52 UTC, Azcarot commented on internal/bubbleface/fileview.go
> +		}
Переделал, обрабатываю

2024-06-13 14:53 UTC, Azcarot commented on internal/bubbleface/bankcarddelete.go
> +	choices, cards = deCypherBankCard(ctx, data.([]storage.BankCardResponse))
Теперь не копирую, передаю параметром вне контекста

2024-06-17 08:53 UTC, tmvrus requested changes
Падают тесты:
```
go test -cover ./...
	github.com/Azcarot/PasswordStorage/cmd/client		coverage: 0.0% of statements
	github.com/Azcarot/PasswordStorage/internal/auth		coverage: 0.0% of statements
	github.com/Azcarot/PasswordStorage/cmd/server		coverage: 0.0% of statements
	github.com/Azcarot/PasswordStorage/internal/bubbleface		coverage: 0.0% of statements
	github.com/Azcarot/PasswordStorage/internal/mock		coverage: 0.0% of statements
	github.com/Azcarot/PasswordStorage/internal/middleware		coverage: 0.0% of statements
	github.com/Azcarot/PasswordStorage/internal/router		coverage: 0.0% of statements
ok  	github.com/Azcarot/PasswordStorage/internal/cfg	0.508s	coverage: 81.8% of statements
ok  	github.com/Azcarot/PasswordStorage/internal/cypher	0.871s	coverage: 5.0% of statements
ok  	github.com/Azcarot/PasswordStorage/internal/handlers	1.059s	coverage: 3.0% of statements
ok  	github.com/Azcarot/PasswordStorage/internal/requests	1.264s	coverage: 61.2% of statements
2024/06/17 11:52:12 failed to connect to `host=localhost user=postgres database=`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)
FAIL	github.com/Azcarot/PasswordStorage/internal/storage	1.158s
FAIL
```

<img width="758" alt="image" src="https://github.com/Azcarot/PasswordStorage/assets/554425/0d9dc2b9-0257-443e-a709-63d80ea1cc76">

2024-06-17 08:53 UTC, tmvrus commented on cmd/server/main.go
> +		panic(err)
тут тоже можно было использовать Fatal

2024-06-17 17:02 UTC, Azcarot commented on cmd/server/main.go
> +		panic(err)
Использую, теперь

2024-06-19 11:18 UTC, tmvrus commented
```
go test ./...
?   	github.com/Azcarot/PasswordStorage/cmd/client	[no test files]
?   	github.com/Azcarot/PasswordStorage/cmd/server	[no test files]
ok  	github.com/Azcarot/PasswordStorage/internal/auth	(cached)
ok  	github.com/Azcarot/PasswordStorage/internal/bubbleface	(cached)
ok  	github.com/Azcarot/PasswordStorage/internal/cfg	(cached)
ok  	github.com/Azcarot/PasswordStorage/internal/cypher	(cached)
ok  	github.com/Azcarot/PasswordStorage/internal/handlers	(cached)
?   	github.com/Azcarot/PasswordStorage/internal/mock	[no test files]
[{{info 2024-06-19 14:17:49.885595 +0300 MSK m=+0.021361168  uri  method GET body <nil> status 200 duration 1.625µs size 13 undefined } []}]
{{info 2024-06-19 14:17:49.885595 +0300 MSK m=+0.021361168  uri  method GET body <nil> status 200 duration 1.625µs size 13 undefined } []}
--- FAIL: TestWithLogging (0.01s)
    logger_test.go:55:
        	Error Trace:	/tmp/PasswordStorage/internal/middleware/logger_test.go:55
        	Error:      	Not equal:
        	            	expected: "uri  method GET body <nil> status 200 duration 0s size 13"
        	            	actual  : "uri  method GET body <nil> status 200 duration 1.625µs size 13"

        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-uri  method GET body <nil> status 200 duration 0s size 13
        	            	+uri  method GET body <nil> status 200 duration 1.625µs size 13
        	Test:       	TestWithLogging
FAIL
FAIL	github.com/Azcarot/PasswordStorage/internal/middleware	0.670s
ok  	github.com/Azcarot/PasswordStorage/internal/requests	(cached)
ok  	github.com/Azcarot/PasswordStorage/internal/router	(cached)
2024/06/19 14:17:51 github.com/testcontainers/testcontainers-go - Connected to docker:
  Server Version: 24.0.6
  API Version: 1.43
  Operating System: Docker Desktop
  Total Memory: 7950 MB
  Resolved Docker Host: unix:///Users/mihail/.docker/run/docker.sock
  Resolved Docker Socket Path: /var/run/docker.sock
  Test SessionID: 4ee0077478f566169238db5892e44d0559523992c980bb1e6cfb79fbdde68deb
  Test ProcessID: dc042fb4-887f-4534-8153-fb3c3eff1b48
2024/06/19 14:17:51 🐳 Creating container for image testcontainers/ryuk:0.7.0
2024/06/19 14:17:51 ✅ Container created: 81b32cd1fecc
2024/06/19 14:17:51 🐳 Starting container: 81b32cd1fecc
2024/06/19 14:17:51 ✅ Container started: 81b32cd1fecc
2024/06/19 14:17:51 🚧 Waiting for container id 81b32cd1fecc image: testcontainers/ryuk:0.7.0. Waiting for: &{Port:8080/tcp timeout:<nil> PollInterval:100ms}
2024/06/19 14:17:51 🔔 Container is ready: 81b32cd1fecc
2024/06/19 14:17:51 🐳 Creating container for image postgres:13
2024/06/19 14:17:51 ✅ Container created: fa4864bbf5ab
2024/06/19 14:17:51 🐳 Starting container: fa4864bbf5ab
2024/06/19 14:17:51 ✅ Container started: fa4864bbf5ab
2024/06/19 14:17:51 🚧 Waiting for container id fa4864bbf5ab image: postgres:13. Waiting for: &{Port:5432/tcp timeout:<nil> PollInterval:100ms}
2024/06/19 14:17:52 🔔 Container is ready: fa4864bbf5ab
--- FAIL: TestNewConn (9.02s)
    --- FAIL: TestNewConn/normal_data (9.02s)
        cards_test.go:249: NewConn() error = failed to connect to `host=localhost user=postgres database=`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused), wantErr false
--- FAIL: TestBankCardStorage_GetRecord (0.00s)
    --- FAIL: TestBankCardStorage_GetRecord/with_login,_no_rows (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x1051dd6bd]

goroutine 109 [running]:
testing.tRunner.func1.2({0x105558960, 0x105bb3d70})
	/usr/local/Cellar/go/1.22.3/libexec/src/testing/testing.go:1631 +0x24a
testing.tRunner.func1()
	/usr/local/Cellar/go/1.22.3/libexec/src/testing/testing.go:1634 +0x377
panic({0x105558960?, 0x105bb3d70?})
	/usr/local/Cellar/go/1.22.3/libexec/src/runtime/panic.go:770 +0x132
github.com/jackc/pgx/v5.(*Conn).Query(0x0, {0x10566bcc0?, 0xc000590960?}, {0x1053ad6b1, 0x66}, {0xc00044d540, 0x2, 0x2})
	/Users/mihail/lib/go/pkg/mod/github.com/jackc/pgx/v5@v5.5.5/conn.go:703 +0x5d
github.com/jackc/pgx/v5.(*Conn).QueryRow(...)
	/Users/mihail/lib/go/pkg/mod/github.com/jackc/pgx/v5@v5.5.5/conn.go:884
github.com/Azcarot/PasswordStorage/internal/storage.(*BankCardStorage).GetRecord(0xc00029be00, {0x10566bcc0, 0xc000590960})
	/tmp/PasswordStorage/internal/storage/cards.go:45 +0x16f
github.com/Azcarot/PasswordStorage/internal/storage.TestBankCardStorage_GetRecord.func1(0xc000746ea0)
	/tmp/PasswordStorage/internal/storage/cards_test.go:281 +0x1a2
testing.tRunner(0xc000746ea0, 0xc000228bd0)
	/usr/local/Cellar/go/1.22.3/libexec/src/testing/testing.go:1689 +0xfb
created by testing.(*T).Run in goroutine 107
	/usr/local/Cellar/go/1.22.3/libexec/src/testing/testing.go:1742 +0x390
FAIL	github.com/Azcarot/PasswordStorage/internal/storage	11.660s
FAIL
```

2024-06-20 07:08 UTC, tmvrus approved these changes

2024-06-20 07:08 UTC, tmvrus commented on internal/auth/auth.go
> +type MyCustomClaims struct {
а есть какой-то смысл в этом типе?
я не нашел

2024-06-20 07:08 UTC, tmvrus commented on internal/bubbleface/filedelete.go
> +var deleteFileHeader string = "Please select file to delete"
string можно было не писать, компилятор сам догадается

2024-06-20 19:23 UTC, merged